name: Fetch and Store News

on:
  # schedule:
  #   - cron: '0 23,5,11 * * *' # 日本時間で8:00, 14:00, 20:00に実行
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      # ニュースデータの取得とFirestore保存を実行
      - name: Upload news to Firestore
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          "https://korean-front-c6081869e69e.herokuapp.com//api/upload-news"