name: Fetch and Store News

on:
  # schedule:
  #   - cron: '0 23,5,11 * * *' # 日本時間で8:00, 14:00, 20:00に実行
  workflow_dispatch:

jobs:
  fetch-news:
    runs-on: ubuntu-latest

    steps:
      # ニュースデータの取得
      - name: Fetch news data
        env:
          NEWS_API_KEY: ${{ secrets.NEWS_API_KEY }}
        run: |
          curl -s "https://newsapi.org/v2/everything?q=korea&apiKey=${NEWS_API_KEY}" -o news.json

      # APIルートにニュースをPOST
      - name: Upload news to Firestore
        env:
          NEXT_PUBLIC_API_URL: ${{ secrets.NEXT_PUBLIC_API_URL }}
        run: |
          curl -X POST \
          -H "Content-Type: application/json" \
          -d @news.json \
          "${NEXT_PUBLIC_API_URL}/api/upload-news"
